// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace EasyRun2022
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidEasyRunPackageString = "e4568a5d-446c-4d1e-b30a-9b1ef8625ffd";
        public static Guid guidEasyRunPackage = new Guid(guidEasyRunPackageString);

        public const string guidEasyRunPackageCmdSetString = "03be6bdd-b20a-4ed1-af8c-7a9cd5f57edc";
        public static Guid guidEasyRunPackageCmdSet = new Guid(guidEasyRunPackageCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int EasyRunToolWindowCommandId = 0x0100;
    }
}